Adjustments

diff --git a/arch_raw_setup b/arch_raw_setup
--- a/arch_raw_setup
+++ b/arch_raw_setup
@@ -133,25 +133,34 @@ then
   hostname=$REPLY
 fi
 
-arch-chroot /mnt/ echo $hostname > /etc/hostname
+arch-chroot /mnt echo $hostname > /etc/hostname
 
-arch-chroot /mnt/ echo LANG=de_DE.UTF-8 > /etc/locale.conf
-arch-chroot /mnt/ echo LC_COLLATE=C >> /etc/locale.conf
-arch-chroot /mnt/ echo LANGUAGE=de_DE >> /etc/locale.conf
+arch-chroot /mnt echo LANG=de_DE.UTF-8 > /etc/locale.conf
+arch-chroot /mnt echo LC_COLLATE=C >> /etc/locale.conf
+arch-chroot /mnt echo LANGUAGE=de_DE >> /etc/locale.conf
 
-arch-chroot /mnt/ ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
+arch-chroot /mnt ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
 
-arch-chroot /mnt/ cp /etc/locale.gen /etc/locale.gen.bak
-arch-chroot /mnt/ sed -i 's/#de_DE.UTF-8/de_DE.UTF-8/g' /etc/locale.gen
-arch-chroot /mnt/ sed -i 's/#de_DE ISO-8859-1/de_DE ISO-8859-1/g' /etc/locale.gen
-arch-chroot /mnt/ sed -i 's/#en_US.UTF-8/en_US.UTF-8/g' /etc/locale.gen
-arch-chroot /mnt/ locale-gen
+arch-chroot /mnt cp /etc/locale.gen /etc/locale.gen.bak
+arch-chroot /mnt sed -i 's/#de_DE.UTF-8/de_DE.UTF-8/g' /etc/locale.gen
+arch-chroot /mnt sed -i 's/#de_DE ISO-8859-1/de_DE ISO-8859-1/g' /etc/locale.gen
+arch-chroot /mnt sed -i 's/#en_US.UTF-8/en_US.UTF-8/g' /etc/locale.gen
+arch-chroot /mnt locale-gen
 
 cp /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
 
-arch-chroot /mnt/ pacman -Sy
+arch-chroot /mnt pacman -Sy
 
-arch-chroot /mnt/ mkinitcpio -p linux
+#make the group wheel ready to use with sudo
+arch-chroot /mnt groupadd wheel
+arch-chroot /mnt sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers
+#make a proxy available for sudo
+arch-chroot /mnt echo "Defaults env_keep += \"http_proxy\"" >> /etc/sudoers
+arch-chroot /mnt echo "Defaults env_keep += \"https_proxy\"" >> /etc/sudoers
+
+echo "Install kernel"
+
+arch-chroot /mnt mkinitcpio -p linux
 
 echo "Set root password..."
 
@@ -163,26 +172,32 @@ then
   rootPass=$REPLY
 fi
 
-arch-chroot /mnt/ sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | passwd
+arch-chroot /mnt sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | passwd
   $rootPass # password
   $rootPass # second time
 EOF
 
 echo "Install GRUB..."
-arch-chroot /mnt/ mount -t efivarfs efivarfs /sys/firmware/efi/efivars
-arch-chroot /mnt/ pacman -Sq grub efibootmgr dosfstools
+arch-chroot /mnt mount -t efivarfs efivarfs /sys/firmware/efi/efivars
+arch-chroot /mnt pacman -Sq grub efibootmgr dosfstools
 
-arch-chroot /mnt/ grub-mkconfig -o /boot/grub/grub.cfg
+arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
 
-arch-chroot /mnt/ grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=arch_grub --recheck --debug
+arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=arch_grub --recheck --debug
 
 if [ ! $? -eq 0 ]
 then
   echo "Error on create boot menu entry, trying again with efibootmgr..."
-  arch-chroot /mnt/ efibootmgr -q -c -d ${installDev} -p 1 -w -L "GRUB: Arch-Linux" -l "\EFI\arch_grub\grubx64.efi"
+  arch-chroot /mnt efibootmgr -q -c -d ${installDev} -p 1 -w -L "GRUB: Arch-Linux" -l "\EFI\arch_grub\grubx64.efi"
+  if [ $? -eq 0 ]
+  then
+    echo "Success"
+  else
+    echo "Error, no boot entry created!"
+  fi
 fi
 
-arch-chroot /mnt/ mkdir -p /boot/grub/locale
-arch-chroot /mnt/ cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
+arch-chroot /mnt mkdir -p /boot/grub/locale
+arch-chroot /mnt cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
 
 echo "Exit installed system. Please reboot now to switch to your fresh arch linux."
